2025-05-13 12:53:43,723 INFO    MainThread:656501 [internal.py:wandb_internal():93] W&B internal server running at pid: 656501, started at: 2025-05-13 12:53:43.723260
2025-05-13 12:53:43,727 DEBUG   HandlerThread:656501 [handler.py:handle_request():140] handle_request: run_start
2025-05-13 12:53:43,728 INFO    WriterThread:656501 [datastore.py:open_for_write():75] open: /home/user/pyo/Rec-with-TKG/wandb/offline-run-20250513_125342-n83csvn3/run-n83csvn3.wandb
2025-05-13 12:53:43,745 DEBUG   HandlerThread:656501 [meta.py:__init__():35] meta init
2025-05-13 12:53:43,745 DEBUG   HandlerThread:656501 [meta.py:__init__():49] meta init done
2025-05-13 12:53:43,745 DEBUG   HandlerThread:656501 [meta.py:probe():209] probe
2025-05-13 12:53:43,752 DEBUG   HandlerThread:656501 [meta.py:_setup_git():199] setup git
2025-05-13 12:53:43,776 DEBUG   HandlerThread:656501 [meta.py:_setup_git():206] setup git done
2025-05-13 12:53:43,777 DEBUG   HandlerThread:656501 [meta.py:_save_pip():53] save pip
2025-05-13 12:53:43,778 DEBUG   HandlerThread:656501 [meta.py:_save_pip():67] save pip done
2025-05-13 12:53:43,778 DEBUG   HandlerThread:656501 [meta.py:_save_conda():74] save conda
2025-05-13 12:53:45,048 DEBUG   HandlerThread:656501 [meta.py:_save_conda():84] save conda done
2025-05-13 12:53:45,048 DEBUG   HandlerThread:656501 [meta.py:probe():247] probe done
2025-05-13 13:14:26,973 WARNING MainThread:656501 [internal.py:wandb_internal():153] Internal process interrupt: 1
2025-05-13 13:14:55,752 WARNING MainThread:656501 [internal.py:wandb_internal():153] Internal process interrupt: 2
2025-05-13 13:14:55,752 ERROR   MainThread:656501 [internal.py:wandb_internal():156] Internal process interrupted.
2025-05-13 13:14:55,965 INFO    SenderThread:656501 [sender.py:finish():1114] shutting down sender
2025-05-13 13:14:56,303 INFO    WriterThread:656501 [datastore.py:close():279] close: /home/user/pyo/Rec-with-TKG/wandb/offline-run-20250513_125342-n83csvn3/run-n83csvn3.wandb
2025-05-13 13:14:56,328 INFO    HandlerThread:656501 [handler.py:finish():806] shutting down handler
2025-05-13 13:14:56,329 INFO    MainThread:656501 [internal.py:handle_exit():80] Internal process exited
